apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-nodejsapp
  labels:
    app: sample-nodejsapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nodejsapp
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: sample-nodejsapp
          image: clarkkent/samplenodejswebapp:latest
          env:
            - name: APP_NAME
              value: "sample-nodejsapp"
            - name: TEST_ME
              value: "Hello, world!"
            - name: K8_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              value: "3333"
          ports:
            - containerPort: 3333
              name: sample-nodejsapp
---
apiVersion: v1
kind: Service
metadata:
  name: sample-nodejsapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: sample-nodejsapp
  selector:
    app: sample-nodejsapp
